// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt6ezuz_QAc6WiOOX7_MetFJWrfnq2Hu0',
    appId: '1:261082612556:web:e8fcb59f2fa0e129fbc5e9',
    messagingSenderId: '261082612556',
    projectId: 'finwise-c9aba',
    authDomain: 'finwise-c9aba.firebaseapp.com',
    storageBucket: 'finwise-c9aba.firebasestorage.app',
    measurementId: 'G-JXT9EHRGWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKpN9zTiFIKtqI2z9n3kEGwnc1vKWQpPk',
    appId: '1:261082612556:android:780a760ca7125d49fbc5e9',
    messagingSenderId: '261082612556',
    projectId: 'finwise-c9aba',
    storageBucket: 'finwise-c9aba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABElvOr0QX2DoA7JjqXbakWwIPOMYTWiw',
    appId: '1:261082612556:ios:f367da006d987d21fbc5e9',
    messagingSenderId: '261082612556',
    projectId: 'finwise-c9aba',
    storageBucket: 'finwise-c9aba.firebasestorage.app',
    iosBundleId: 'com.example.finwiseAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABElvOr0QX2DoA7JjqXbakWwIPOMYTWiw',
    appId: '1:261082612556:ios:f367da006d987d21fbc5e9',
    messagingSenderId: '261082612556',
    projectId: 'finwise-c9aba',
    storageBucket: 'finwise-c9aba.firebasestorage.app',
    iosBundleId: 'com.example.finwiseAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt6ezuz_QAc6WiOOX7_MetFJWrfnq2Hu0',
    appId: '1:261082612556:web:97ffdf2e31a74137fbc5e9',
    messagingSenderId: '261082612556',
    projectId: 'finwise-c9aba',
    authDomain: 'finwise-c9aba.firebaseapp.com',
    storageBucket: 'finwise-c9aba.firebasestorage.app',
    measurementId: 'G-HSK240GSN1',
  );
}
